# Generated by Django 5.0.6 on 2024-05-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('condition', models.CharField(choices=[('Working', 'working'), ('No_Working', 'no_working')], default='Working', max_length=15)),
            ],
        ),
    ]
