# Generated by Django 5.0.6 on 2024-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_combine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralEndorsements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('weight', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OtherEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('condition', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('condition', models.CharField(choices=[('Рабочий', 'Рабочий'), ('Нерабочий', 'Нерабочий')], default='Рабочий', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='combine',
            name='condition',
            field=models.CharField(choices=[('Рабочий', 'Рабочий'), ('Нерабочий', 'Нерабочий')], default='Рабочий', max_length=15),
        ),
    ]
