# Generated by Django 5.0.6 on 2024-05-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_mineralendorsements_otherequipments_tractor_workers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='age',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
