# Generated by Django 5.0.6 on 2024-05-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_workers_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCombine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('driver', models.BooleanField(default=False)),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdTractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('driver', models.BooleanField(default=False)),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('quickly', models.BooleanField(default=False)),
            ],
        ),
    ]
